eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

ribbon:
  eureka:
    enabled: true

spring:
  application:
    name: jiuyi_feign_robot
  main:
    allow-bean-definition-overriding: true

feign:
  hystrix:
    enabled: true

